runtime: python311
entrypoint: python app.py

env_variables:
  SECRET_KEY: "your-secure-secret-key-here"
  FLASK_ENV: "production"

automatic_scaling:
  target_cpu_utilization: 0.6
  min_instances: 1
  max_instances: 10

resources:
  cpu: 1
  memory_gb: 0.5
  disk_size_gb: 10

handlers:
  - url: /static
    static_dir: static
  - url: /.*
    script: auto 