name: Deploy Nord Stern Car Numbers to Cloud Run

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

env:
  PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}
  REGION: us-central1
  SERVICE_NAME: nord-stern-car-numbers

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ secrets.GCP_PROJECT_ID }}
        service_account_key: ${{ secrets.GCP_SA_KEY }}
        export_default_credentials: true
    
    - name: Authorize Docker push
      run: gcloud auth configure-docker
    
    - name: Build and Deploy to Cloud Run
      run: |
        gcloud builds submit --config cloudbuild.yaml .
    
    - name: Show Service URL
      run: |
        echo "✅ Deployment completed!"
        echo "🌐 Service URL: https://$SERVICE_NAME-$(echo $PROJECT_ID | cut -d'-' -f1)-$REGION.a.run.app" 